package expo.modules.kotlin

import android.app.Activity
import expo.modules.kotlin.exception.Exceptions

// Lightweight shim to provide extension properties that are normally generated by Expo's
// KSP/codegen. Placing this file in an in-repo included-build and adding it to module
// sourceSets allows us to compile modules that reference these helpers without
// modifying node_modules directly.

val AppContext.throwingActivity: Activity
  get() = currentActivity ?: throw Exceptions.ReactContextLost()
